# Generated by Django 5.2.5 on 2025-09-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("online_training", "0004_course_owner_lesson_owner"),
        ("users", "0004_folowers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Folowers",
            new_name="Followers",
        ),
    ]
