# Generated by Django 5.2.5 on 2025-09-10 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_donation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ccылка на оплату"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Id сессии"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
