# Generated by Django 5.2.5 on 2025-08-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_training", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
