# Generated by Django 5.2.5 on 2025-08-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_training", "0002_alter_lesson_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="online_training.course",
                verbose_name="Курс",
            ),
        ),
    ]
