name: drf_project

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root
      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          run: |
            python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Установка необходимых пакетов на сервере
        run: |
          ssh -o StrictHostKeyChecking=no -vT ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip
          EOF
      - name: Установка зависимостей
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ${{ secrets.DEPLOY_DIR }}
          sudo apt install curl
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.create true
          poetry install --no-root
          EOF

#      - name: Sync project to server
#        run: |
#          ssh -o StrictHostKeyChecking=no -vT ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#          sudo apt-get update
#          sudo apt-get install -y python3-venv python3-pip
#          EOF
#      - name: Install dependencies on server
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#          cd ${{ secrets.DEPLOY_DIR }}
#          sudo apt install curl
#          curl -sSL https://install.python-poetry.org | python3 -
#          poetry config virtualenvs.create true
#          poetry install --no-root
#          EOF


#  deploy:
#    runs-on: ubuntu-latest
#    needs: test
#    env:
#      SECRET_KEY: ${{ secrets.SECRET_KEY }}
#      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
#      DATABASE_USER: ${{ secrets.DATABASE_USER }}
#      PASSWORD: ${{ secrets.PASSWORD }}
#      HOST: ${{ secrets.HOST }}
#      PORT: ${{ secrets.PORT }}
#
#    steps:
#    - name: Set up SSH
#      uses: webfactory/ssh-agent@v0.9.0
#      with:
#         ssh-private-key: ${{ secrets.SSH_KEY }}
#    - name: Add server to known_hosts
#      run: |
#        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
#    - name: Sync project to server
#      run: |
#        rsync -avz --exclude '__pycache__' . ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_DIR }}
#         ssh -o StrictHostKeyChecking=no -vT ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}
#        rsync -avz --delete --exclude='.git' ./ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_DIR }}
#        sudo apt-get update
#        sudo apt-get upgrade
#    - name: Install dependencies on server
#      run: |
#        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#          cd ${{ secrets.DEPLOY_DIR }}
#          poetry install
#        EOF

#    steps:
#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.9.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_KEY }}
#
#      - name: Sync project to server
#        run: |
#          sudo rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/alex/
#      - name: Deploy to server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            cd ~/home/alex/
#            git pull # Скачать последние изменения
#            python manage.py collectstatic --noinput
#            sudo systemctl restart your_app_service
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#          cd /home/alex/
#            git pull origin main
#            python manage.py migrate
#            poetry install
#            python manage.py collectstatic --noinput
#            sudo systemctl restart your_app_service
#          EOF

#  build:
#    needs: test
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v3
#
#      -  name: Log in Docker hub
#         run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#
#      -  name: Build and push Docker images
#         run: |
#           docker compose build
#           docker compose push
#
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.9.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_KEY }}
#
#      - name: Deploy to server
#        run: |
#          ssh -o StrictHostKeyChecking=no -vT ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#          docker pull ${{ secrets.DOCKER_USERNAME  }}/myapp:${{ github.sha }}
#          docker stop myapp || true
#          docker rm myapp || true
#          docker run -d --name myapp -p 80:8000 ${{ secrets.SSH_USER }}/myapp:${{ github.sha }}
#          EOF